### ISSUE TITLE
Add 1.19.3 compatibility

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/AggressiveAnimals#3]
**Is your feature request related to a problem? Please describe.**
AggressiveAnimals 1.1.0 is incompatible with Paper/Spigot 1.19.3

On server start-up
```
[13:45:11] [Server thread/INFO]: [AggressiveAnimals] Loading AggressiveAnimals v1.1.0
[13:48:07] [Server thread/INFO]: [AggressiveAnimals] Enabling AggressiveAnimals v1.1.0
[13:48:07] [Server thread/ERROR]: Error occurred while enabling AggressiveAnimals v1.1.0 (Is it up to date?)
java.lang.IllegalArgumentException: Plugin version not supported: null
        at dev.ratas.aggressiveanimals.nms.NMSResolver.getSetter(NMSResolver.java:21) ~[AggressiveAnimals-1.1.0.jar:?]
        at dev.ratas.aggressiveanimals.main.AggressiveAnimals.loadDataFromFile(AggressiveAnimals.java:51) ~[AggressiveAnimals-1.1.0.jar:?]
        at dev.ratas.aggressiveanimals.main.AggressiveAnimals.pluginEnabled(AggressiveAnimals.java:62) ~[AggressiveAnimals-1.1.0.jar:?]
        at dev.ratas.aggressiveanimals.main.core.impl.SlimeDogCore.onEnable(SlimeDogCore.java:55) ~[AggressiveAnimals-1.1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Describe the solution you'd like**
Update to support 1.19.3.

**Comment by SlimeDog** [comment]
Resolved with AggressiveAnimals 1.2.0
