### ISSUE TITLE
NPE on stop tracking

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/AggressiveAnimals#63]
User identified this error
```
[15:52:21 WARN]: [AggressiveAnimals] Task #99 for AggressiveAnimals v1.5.2 generated an exception
java.lang.[NullPointerException](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+nullpointerexception): Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because the return value of "net.minecraft.world.entity.EntityInsentient.a(net.minecraft.world.entity.ai.attributes.AttributeBase)" is null
        at dev.ratas.aggressiveanimals.aggressive.nms_v1_20_R1.NMSAggressivitySetter.stopTracking(NMSAggressivitySetter.java:141) ~[AggressiveAnimals-1.5.2.jar:?]
        at dev.ratas.aggressiveanimals.aggressive.AggressivityManager.stopTracking(AggressivityManager.java:118) ~[AggressiveAnimals-1.5.2.jar:?]
        at dev.ratas.aggressiveanimals.aggressive.timers.AggressivityMaintainer.process(AggressivityMaintainer.java:19) ~[AggressiveAnimals-1.5.2.jar:?]
        at dev.ratas.aggressiveanimals.aggressive.timers.AggressivityMaintainer.process(AggressivityMaintainer.java:8) ~[AggressiveAnimals-1.5.2.jar:?]
        at dev.ratas.aggressiveanimals.aggressive.timers.AbstractQueuedRunnable.run(AbstractQueuedRunnable.java:27) ~[AggressiveAnimals-1.5.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.jar:git-Paper-17]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.jar:git-Paper-17]
        at java.lang.[Thread](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+thread).run([Thread](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+thread).java:833) ~[?:?]
```
but declined to provide additional information as requested.

**Comment by SlimeDog** [comment]
Issue should be resolved with AggressiveAninmals 1.6.1.
